const LOADED_COMMENTS = 5;
const MAX_COMMENTS_LENGTH = 140;
const MAX_TEGS_COUNT = 5;
const MAX_SCALE_RANGE = 100;
const MIN_SCALE_RANGE = 25;
const NUMBER_OF_PHOTOS = 10;
const RERENDER_DELAYS = 500;

export{LOADED_COMMENTS};
export{MAX_COMMENTS_LENGTH, MAX_TEGS_COUNT};
export{MIN_SCALE_RANGE, MAX_SCALE_RANGE};
export {NUMBER_OF_PHOTOS};
export {RERENDER_DELAYS};
